# .github/workflows/update_db.yml

name: Update Vector DB

# main 브랜치의 'data' 폴더에 변경이 생길 때마다 실행
on:
  push:
    branches:
      - main
    paths:
      - 'data/**'

jobs:
  build-vector-db:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드를 서버로 가져옴
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 필요한 라이브러리 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Vector DB 생성 스크립트 실행
      - name: Create Vector DB
        run: python create_vector_db.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # 5. 변경된 DB 파일을 GitHub 저장소에 다시 저장(Commit & Push)
      - name: Commit and push if it changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add faiss_index/
          git diff --staged --quiet || git commit -m "Update Vector DB"
          git push