# .github/workflows/update.yml (최종 수정 버전)

name: Update Vector DB

on:
  # 1. 스케줄링 실행: 매일 0시(UTC)에 자동으로 실행 (한국 시간 오전 9시)
  schedule:
    - cron: '0 0 * * *'
  
  # 2. 수동 실행: GitHub Actions 탭에서 "Run workflow" 버튼으로 즉시 실행 가능
  workflow_dispatch:

jobs:
  build-vector-db:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드를 서버로 가져옴
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 필요한 라이브러리 설치 (NumPy, unstructured 문제 해결 포함)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "numpy<2.0"                  # NumPy 버전 호환성 문제 해결
          pip install "unstructured[pdf,pptx]"      # PDF, PPTX 처리 라이브러리 설치
          pip install -r requirements.txt         # 나머지 라이브러리 설치

      # 4. Google Drive 인증 파일 생성 (Secret 사용)
      - name: Create gdrive-credentials.json
        run: echo "${{ secrets.GDRIVE_CREDENTIALS_JSON }}" > gdrive-credentials.json
        shell: bash

      # 5. Vector DB 생성 스크립트 실행 (모든 Secret 전달)
      - name: Create Vector DB
        run: |
          python create_notion_vector_db.py
          python create_gdrive_vector_db.py
          python create_github_vector_db.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_PAGE_ID_1: ${{ secrets.NOTION_PAGE_ID_1 }}
          NOTION_PAGE_ID_2: ${{ secrets.NOTION_PAGE_ID_2 }}
          NOTION_PAGE_ID_3: ${{ secrets.NOTION_PAGE_ID_3 }}
          NOTION_PAGE_ID_4: ${{ secrets.NOTION_PAGE_ID_4 }}
          NOTION_PAGE_ID_5: ${{ secrets.NOTION_PAGE_ID_5 }}
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}

      # 6. Migrate FAISS to Chroma
      - name: Migrate FAISS to Chroma
        run: |
          python f2c.py --faiss_dir notion_faiss_index --chroma_dir chroma_notion --collection notion --normalize
          python f2c.py --faiss_dir gdrive_faiss_index --chroma_dir chroma_gdrive --collection gdrive --normalize
          python f2c.py --faiss_dir github_faiss_index --chroma_dir chroma_github --collection github --normalize

      # 7. 변경된 DB 파일을 GitHub 저장소에 다시 저장(Commit & Push)
      - name: Commit and push if it changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add chroma_*/
          git diff --staged --quiet || (git commit -m "Update Vector DB" && git push)